<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: brian
 * Date: Sun, 05 Apr 2020 18:59:23 +0000
 */


$conf['authtype'] = 'oauth';
$conf['plugin']['authmysql']['TablesToLock'] = array();
$conf['plugin']['oauth']['mcneelaccounts-key'] = 'wiki_mcneel_com';
$conf['plugin']['oauth']['mcneelaccounts-secret'] = '0FqZxOY0kSkVNwBQpnaGkig6pOUa1Lc';
$conf['plugin']['oauth']['mcneelaccounts-userinfourl'] = 'https://accounts.rhino3d.com/oauth2/userinfo';
$conf['plugin']['oauth']['rhinoaccounts-key'] = 'wiki_mcneel_com';
$conf['plugin']['oauth']['rhinoaccounts-secret'] = '0FqZxOY0kSkVNwBQpnaGkig6pOUa1Lc';
$conf['plugin']['oauth']['rhinoaccounts-userinfourl'] = 'https://accounts.rhino3d.com/oauth2/userinfo';
$conf['plugin']['oauth']['singleService'] = 'RhinoAccounts';


// end auto-generated content

